{% set name = "opentelemetry-util-http" %}
{% set version = "0.32b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-util-http-{{ version }}.tar.gz
  sha256: 7bbf5e63b33ace1511eb4421e0f28089f2d86a0419caded3cc34793fdb89cc66

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - opentelemetry
    - opentelemetry.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/util/opentelemetry-util-http
  summary: Web util for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
