{% set name = "opentelemetry-util-http" %}
{% set version = "0.25b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-util-http-{{ version }}.tar.gz
  sha256: b6c43a365a866dd814e2902cc52bc2657d6abd8d831b99e11d67b9957b0a4398

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asgiref ~=3.0
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.24b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0

test:
  imports:
    - opentelemetry
    - opentelemetry.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/util/opentelemetry-util-http
  summary: Web util for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
