{% set name = "opentelemetry-util-http" %}
{% set version = "0.59b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ae66ee91be31938d832f3b4bc4eb8a911f6eddd38969c4a871b1230db2a0a560

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python

# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
{% set ignore_tests = " --ignore=tests/test_http_base.py" %}
test:
  source_files:
    - tests
  imports:
    - opentelemetry.util.http
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }}
  requires:
    - pip
    - pytest >=7.4.4
    - opentelemetry-semantic-conventions =={{ version }}
    - opentelemetry-instrumentation =={{ version }}
    - wrapt

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/util/opentelemetry-util-http
  summary: Web util for OpenTelemetry
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library provides ASGI, WSGI middleware and other HTTP-related functionality that is common to instrumented
    web frameworks (such as Django, Starlette, FastAPI, etc.) to track requests timing through OpenTelemetry.
  doc_url: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/util/opentelemetry-util-http/README.rst
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/util/opentelemetry-util-http

extra:
  recipe-maintainers:
    - mariusvniekerk
